### ISSUE TITLE
[Papercut] Add configuration under $HOME/.config/requestr 

### ISSUE THREAD

**Issue by segfaultsourcery** [Semptic/requestr#8]
It'd be a lot easier to use this program if there was a way to tell it one or more paths where my yaml files are stored.

It would mean I could type something like 

```bash
requestr my-awesome-request --env production -p a=b
```

instead of

```bash
requestr ~/unbelievably/deep/nesting/where/I/store/my-awesome-request --env ~/unbelievably/deep/nesting/where/I/store/environments/like/production -p a=b
```

```toml
[defaults]
script-path = "~/unbelievably/deep/nesting/where/I/store"
env-path = "~/unbelievably/deep/nesting/where/I/store/environments/like/production"
```
